### ISSUE TITLE
Excessive training time

### ISSUE THREAD

**Issue by sungnyun** [YUCHEN005/UniVPM#3]
Hello again. I'm trying to train UniVPM model on my side.
I am using the same config file you have uploaded, and similar command as AV-HuBERT repo.

The problem is that training UniVPM entails **excessive amount of training time**.
It looks like this issue stems from constantly updating viseme/phoneme bank and initializing the cluster centers.

It keeps calling the [bank update part](https://github.com/YUCHEN005/UniVPM/blob/master/avhubert/hubert.py#L924-L938) and [initializing cluster centers](https://github.com/YUCHEN005/UniVPM/blob/master/avhubert/hubert.py#L469-L480), which is I'm not sure why it should update once every 10 iterations (random prob. is 0.1).
Have not you encountered any issues on slow training like I do?

Thanks.

**Comment by YUCHEN005** [comment]
Hi, I have not met this issue, actually from my observation the process of clustering only take a small portion of training time..

"why it should update once every 10 iterations (random prob. is 0.1)" --> to save time of clustering, no need to update frequently, you can adjust it to save time
